service: serverless-cicd1
provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  timeout: 60
  memorySize: 256


custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  simple-nltk:
    handler: handler.lambda_handler
    events:
      - http:
          path: nltk
          method: post

plugins:
  - serverless-python-requirements
